# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1.0
maven_group = org.thinkingstudio
archives_name = confirmquit
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.20.6
yarn_mappings = 1.20.6+build.3

# Dependencies
fabric_loader_version = 0.18.1
fabric_api_version = 0.100.8+1.20.6
neoforge_version = 20.6.139
cloth_config_version = 14.0.139
modmenu_version = 10.0.0
