# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1.0
maven_group = org.thinkingstudio
archives_name = RuSureQuit
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.1

# Dependencies
fabric_loader_version = 0.18.1
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.10
cloth_config_version = 11.1.136
modmenu_version = 7.2.2

curseforge_id = 1400499
modrinth_id = Elex0J7Z
