modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "confirmquit"
version = "${version}"
displayName = "ConfirmQuit"
authors = "TexTrue, ThinkingStudio, CaaMoe, Xiao_Cozi"
description = '''
QuitConfirm unofficial multi-modloader port.
Add a quit confirm screen/toast to avoid mistakenly quitting the game.
'''
logoFile = "assets/confirmquit/icon.png"

[[dependencies.confirmquit]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.confirmquit]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.confirmquit]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
