modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "rusurequit"
version = "${version}"
displayName = "RuSureQuit"
displayURL = "https://github.com/ThinkingStudios/RuSureQuit"
authors = "TexTrue, ThinkingStudio, CaaMoe, Xiao_Cozi"
description = '''
QuitConfirm unofficial multi-modloader port.
Add a quit confirm screen/toast to avoid mistakenly quitting the game.
'''
logoFile = "assets/rusurequit/icon.png"

[[mixins]]
config = "rusurequit.mixins.json"

[[dependencies.rusurequit]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rusurequit]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rusurequit]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
